### PR TITLE
to synchronize the repositories

### PR DESCRIPTION
**Pull request by go0d0ne**
no actual changes, just sync.

### CODE REVIEW

**Comment by NotTsunami** [comment]
What was the point of this? Now there are a lot of duplicate commits and a confusing history. There are plenty of other ways to synchronize repos that don't lead to an awful commit history.

**Comment by go0d0ne** [comment]
> 
> 
> What was the point of this? Now there are a lot of duplicate commits and a confusing history. There are plenty of other ways to synchronize repos that don't lead to an awful commit history.

be free to propose one.

but let's not lose our heads over such an insignificant detail... this is not linux kernel code, why would anyone lose their mind over commit history "looks". it's bound to be ugly eventually anyway.

**Comment by NotTsunami** [comment]
> > What was the point of this? Now there are a lot of duplicate commits and a confusing history. There are plenty of other ways to synchronize repos that don't lead to an awful commit history.
> 
> be free to propose one.
> 
> but let's not lose our heads over such an insignificant detail... this is not linux kernel code, why would anyone lose their mind over commit history "looks". it's bound to be ugly eventually anyway.

I wouldn't so much call it an insignificant detail, I enjoy this patch for the Metro skin and do look at each diff. This PR just made it confusing to tell what was changed. My issue was that this led to many duplicate commits. I just ask nicely that you sync your tree properly (git is an extremely powerful tool, there are plenty of ways to sync without having to make PRs on your own repo each time upstream is updated), not losing my head at all :)

**Comment by NotTsunami** [comment]
Also wait, this didn't even have any changes at all, what in the world _was_ the point of this? I'm guessing you meant to merge upstream into your fork and sent in a PR on accident here?

**Comment by go0d0ne** [comment]
> Also wait, this didn't even have any changes at all, what in the world _was_ the point of this?

the purpose was to avoid my fork showing as much more progressed than RS' (by showing multiple commits from upstream, which were around 10 and counting). it was confusing and misleading.

>  I'm guessing you meant to merge upstream into your fork and sent in a PR on accident here?

it was a wrong guess.

> > > There are plenty of other ways to synchronize repos that don't lead to an awful commit history.
> >
> > be free to propose one.
>
> git is an extremely powerful tool, there are plenty of ways to sync without having to make PRs on your own repo each time upstream is updated

and which of those "plenty" other ways would u propose?
something that web interface supports - preferable.
thank u for the input.

btw,
> This PR just made it confusing to tell what was changed. My issue was that this led to many duplicate commits.

decide what u r concentrating on, commit changes or commit history "prettiness".
I cannot to think u want both, but that's rarely the case even with much more serious gits than this one - having dozens of maintainers.

I apologize for making commit history ugly; it was simply the quickest and most painless way to do it at that time.

coding isn't always the most pretty of things to look at, yet alone tools behind it. if I saw the same, I would have just ignored it, instead of wasting my time commenting, repeating my own sentences, with "plenty" suggestions and no concrete details on how to do things otherwise.

to make it simple - if u want to have it done in a different way, suggest one.

**Comment by Stanzilla** [comment]
Hey there, this is a good article on the topic https://www.atlassian.com/git/tutorials/merging-vs-rebasing

**Comment by go0d0ne** [comment]
> Hey there, this is a good article on the topic https://www.atlassian.com/git/tutorials/merging-vs-rebasing

thank u for the article. I'm already aware of it, having read it, and some other with same topic, long time ago.

however, rebase is a dangerous tool as it rewrites commit history too much.
thus, it is not good for continuous sync between master and forks. it's somewhat good for work on features (while making dubious discussions on how much), but that's not what we have here.

anybody who disagrees or has another solution, please simply write commands or workflow u believe we should use. it will speed things up, instead of reading a long, complex and sometimes confusing articles on git features.
thank u.

**Pull request merged**
