### PR TITLE
fix layout missing Steam Play items for Linux clients

### PR DESCRIPTION
**Pull request by mainmachine**
There's also an issue for the "gamespage_details_compat_subheader.layout" file not showing body text correctly (text is cut off) but I am not sure how to address it

### CODE REVIEW

**Comment by go0d0ne** [comment]
can we have a screenshot?

**Comment by redsigma** [comment]
This has been fixed.

**Comment by mainmachine** [comment]
Thank you for those changes, they work well! I've found another issue, unfortunately. Not sure if it makes sense to report here or not, but here goes.

I also use the "High DPI" patches, and unfortunately those mess up the formatting in "resource/layout/gamespage_details_compat_subheader.layout"

Here's what I'm seeing:

screenshot from 2019-02-17 21-36-37

...and here's when I hack in some of the default Steam skin bits:

screenshot from 2019-02-17 23-01-08

This is not my specialty, I'm sure it can be done better: 

```
@@ -11,8 +11,8 @@
 	}
 	layout
 	{
-		region { name=body margin=8 width=max height=max }
+		region { name="header" margin=8 width=max height=max }
 
-		place { control=compatdescription x=52 y=12 region=body width=max }
+		place { control=compatdescription x=52 y=12 region=body margin-top=0 margin-left=0 margin-right=0 width=max }
 	}
 }
```

**Comment by go0d0ne** [comment]
it's best to make another issue or pull request with these newest details.

**Pull request closed without merging**
