### PR TITLE
Added some basic instructions to the README

### PR DESCRIPTION
**Pull request by djreisch**
Just added some basic instructions. Sorry for the multiple commits, had to get formatting just right. They are basic instructions, not the best but better then nothing for the newbie.

### CODE REVIEW

**Comment by go0d0ne** [comment]
unfortunately, these instructions r insufficient:
1. original metro for steam installation isn't mentioned, which leaves the installed skin in bad state.
2. installation of extras is not detailed.
3. headline should be smaller, like the headline of license section.

**Comment by djreisch** [comment]
Correct me if I’m wrong, but the original metro skin doesn’t need to be installed.

-Daniel

**Comment by go0d0ne** [comment]
u r wrong.

**Comment by djreisch** [comment]
Does the full version of Metro have to be placed and then this repo copied over? Because I installed this repo plain (per the instructions I wrote) and compared to Metro on older versions of Steam. Seems to be fully functional.

What would be different had I had the original Metro files?

**Comment by GenesisFR** [comment]
Yes you need to put the original Metro skin then the patch: https://steamcommunity.com/groups/metroskin/discussions/0/141136086931804907/

I just tried with the patch files only and some things are missing (like game categories or checkboxes).

**Comment by djreisch** [comment]
Well see what I’m saying, is I didn’t put the original files for Metro in there first, however the skin looks complete. What functionalities am I missing?

-Daniel

**Comment by redsigma** [comment]
I updated the readme just a minute ago and it should explain where you can find the instructions. If you don't apply the official metro you will have a lot of missing icons and some misaligned panels.

**Comment by GenesisFR** [comment]
Thank you for taking the time to do it either way, I'm sure others think the same.

**Pull request closed without merging**
